In [7]:
import numpy as np

a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
#Get a specific element[r, c] starts with 0!!!!
a[1, 2]

10

In [4]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
#Get a specific column
a[:,0 ]

array([1, 8])

In [6]:
#[row, startindex:endindex:stepsize]
print(a[0, 1:6:2])
a[0, 1:-1:2]

[2 4 6]


array([2, 4, 6])

In [7]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [8]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [9]:
#3d example
m = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
#Get specific element[#element, row, col]
m[0,1,0]

4

In [11]:
#Replace (same dimension!)[#element,row,col]
m[:,1,:] = [[9,9,9],[8,8,8]]
print(m)

[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]
