In [11]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])

In [12]:
a + 2

array([3, 4, 5])

In [13]:
a - 2

array([-1,  0,  1])

In [14]:
a * 2

array([2, 4, 6])

In [15]:
a / 2

array([0.5, 1. , 1.5])

In [16]:
a + b

array([2, 2, 4])

In [17]:
a ** 2

array([1, 4, 9])

In [18]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [20]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])