In [4]:
import numpy as np
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [6]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [8]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
print(stats)
np.min(stats, axis = 1)

[[1 2 3]
 [4 5 6]]


array([1, 4])

In [14]:
print(np.max(stats))
np.max(stats, axis = 1)

6


array([3, 6])

In [16]:
print(np.sum(stats))
np.sum(stats, axis = 1)

21


array([ 6, 15])

In [21]:
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
print(before.shape)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [37]:
filedata = np.genfromtxt('data.txt', delimiter = '')
filedata = filedata.astype('int32')
print(filedata > 50)
filedata[filedata > 50]

[[ True False  True  True False False False  True False  True False  True
   True False  True False  True False]
 [False  True False  True  True False  True False False  True False False
   True False  True  True False  True]
 [False False  True False  True  True False  True  True False  True False
   True False False  True False False]]


array([83, 67, 92, 76, 54, 88, 60, 71, 95, 79, 58, 90, 73, 69, 84, 52, 98,
       66, 86, 55, 93, 62, 74, 80, 96, 68], dtype=int32)

In [ ]:
#52.00