In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [27]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [28]:
#Get dimension
print(a.ndim)
b.ndim

1


2

In [29]:
#Get Shape
print(a.shape)
b.shape

(3,)


(2, 3)

In [30]:
#Get type
print(a.dtype)
b.dtype

int64


dtype('float64')

In [31]:
a2 = np.array([1,2,3], dtype='int16')
a2.dtype

dtype('int16')

In [32]:
#Get size
print(a.itemsize)
a2.itemsize

8


2

In [34]:
#Get total size
print(a.size * a.itemsize)
b.size * b.itemsize

24


48