In [29]:
from numpy.ma.core import shape
%run -i ./02_accesing.ipynb
import numpy as np
import sys
import os
a

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]


array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [30]:
#All 0s Matrix (rows, cols)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#All 1s Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [32]:
#Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [33]:
#Any other number (full like)
print(np.full_like(a, 4))
np.full(a.shape, 4)

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
#Random decimal numbers
print(np.random.rand(4,2))
np.random.random_sample(a.shape)

[[0.62856433 0.7677983 ]
 [0.20144388 0.47103527]
 [0.18411286 0.09659699]
 [0.91771221 0.46835934]]


array([[0.42893745, 0.44903921, 0.78927744, 0.10375321, 0.45277419,
        0.68539305, 0.83008564],
       [0.20853353, 0.98579267, 0.81046723, 0.78513392, 0.57443366,
        0.26687641, 0.10912128]])

In [35]:
#Random integral values
np.random.randint(-4,8, size=(3,3))

array([[ 6,  3,  3],
       [ 0, -2,  4],
       [ 1,  7,  6]])

In [36]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
#CAUTION COPYING ARRAYS!!!
a = [1,2,3]
b = a
c = a.copy()
print(b)
print(c)
b[0] = 100
c[0] = 200
print(b)
print(c)
print(a)
# a <==> b

[1, 2, 3]
[1, 2, 3]
[100, 2, 3]
[200, 2, 3]
[100, 2, 3]
