In [1]:
import numpy as np
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [2]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [3]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
print(stats)
np.min(stats, axis = 1)

[[1 2 3]
 [4 5 6]]


array([1, 4])

In [5]:
print(np.max(stats))
np.max(stats, axis = 1)

6


array([3, 6])

In [6]:
print(np.sum(stats))
np.sum(stats, axis = 1)

21


array([ 6, 15])

In [7]:
before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
print(before.shape)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [10]:
filedata = np.genfromtxt('data.txt', delimiter = '')
filedata = filedata.astype('int32')
print(filedata > 50)
filedata[filedata > 50]

[[ True False  True  True False False False  True False  True False  True
   True False  True False  True False]
 [False  True False  True  True False  True False False  True False False
   True False  True  True False  True]
 [False False  True False  True  True False  True  True False  True False
   True False False  True False False]]


array([83, 67, 92, 76, 54, 88, 60, 71, 95, 79, 58, 90, 73, 69, 84, 52, 98,
       66, 86, 55, 93, 62, 74, 80, 96, 68], dtype=int32)

In [18]:
# You can index with a list in MunPY
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a[[2, 3, 9]] # print the 2nd, 3th and 9th element FIRST ONE IS 0

array([ 3,  4, 10])

In [21]:
print(np.any(filedata > 50, axis = 0))
np.all(filedata > 50, axis = 0)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True]


array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False])

In [23]:
((filedata > 50) & (filedata < 100))

array([[ True, False,  True,  True, False, False, False,  True, False,
         True, False,  True,  True, False,  True, False,  True, False],
       [False,  True, False,  True,  True, False,  True, False, False,
         True, False, False,  True, False,  True,  True, False,  True],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True, False,  True, False, False,  True, False, False]])

In [60]:
matrix = np.arange(1, 31).reshape(6, 5)
print(matrix)
subMatrix = matrix[2:4, 0:2] # Remember start => end + 1, [row, col]
print(subMatrix)
sub2 = matrix[[0,1,2,3],[1,2,3,4]] # pares (0,1),(1,2),(2,3),(3,4)
print(sub2)
sub3 = matrix[[0,4,5], 3:] # row 0,4 & 5 position 3 till the end (5)
print(sub3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]


In [84]:
random_mat = np.random.randint(1, 1000, (10,10))
print(random_mat)
print(np.mean(random_mat)) # Media aritmética
print(np.std(random_mat)) # Desviación estandard
print(random_mat.shape)
traspuesta = random_mat.T # traspuesta = np.transpose(random_mat)
print(traspuesta)
print(traspuesta)

[[623  50 530 499 588 630 861 410 448  19]
 [647 684 481   5 704 981 507 158 263 705]
 [198 199 681 242 857 391 522 637 349 798]
 [771 266 654 419  71 714 396 456 385  81]
 [973 320 691 446 430 256 971 731 752 595]
 [645 981  86 711 826  39 611  70 184 462]
 [600 128   3 260 217 557 999 768 944 274]
 [437 957 839 781  47 700 633 532 549 148]
 [828 165 438 599 933 979 911 849   8 539]
 [755 359 166 279 463 597 312 278 168 627]]
502.86
280.93426348525026
(10, 10)
[[623 647 198 771 973 645 600 437 828 755]
 [ 50 684 199 266 320 981 128 957 165 359]
 [530 481 681 654 691  86   3 839 438 166]
 [499   5 242 419 446 711 260 781 599 279]
 [588 704 857  71 430 826 217  47 933 463]
 [630 981 391 714 256  39 557 700 979 597]
 [861 507 522 396 971 611 999 633 911 312]
 [410 158 637 456 731  70 768 532 849 278]
 [448 263 349 385 752 184 944 549   8 168]
 [ 19 705 798  81 595 462 274 148 539 627]]
[[623 647 198 771 973 645 600 437 828 755]
 [ 50 684 199 266 320 981 128 957 165 359]
 [530 481 681 654